import * as vscode from "vscode"
import { ArtifactTimingStorage } from "../utils/artifactTimingStorage"

export class ArtifactTimingCodeLensProvider implements vscode.CodeLensProvider {
	private _onDidChangeCodeLenses = new vscode.EventEmitter<void>()
	public readonly onDidChangeCodeLenses = this._onDidChangeCodeLenses.event

	constructor(private storage: ArtifactTimingStorage) {}

	provideCodeLenses(
		document: vscode.TextDocument,
		token: vscode.CancellationToken,
	): vscode.CodeLens[] | Thenable<vscode.CodeLens[]> {
		// If editing is in progress, show editing lens with finish action
		const editingStart = this.storage.getEditingStart(document.uri.fsPath)
		if (editingStart) {
			const range = new vscode.Range(0, 0, 0, 0)
			const codeLens = new vscode.CodeLens(range, {
				title: "📝 Редактирование… • Завершить редактирование",
				command: "ide-bas.finishEditing",
				arguments: [document.uri.fsPath],
				tooltip: "Завершить отсчет времени редактирования",
			})
			return [codeLens]
		}

		const summary = this.storage.getAggregatedTiming(document.uri.fsPath)

		if (!summary) {
			// No timing data → don't show CodeLens
			return []
		}

		const formatMinutes = (ms: number) => `${(ms / 60000).toFixed(1)} мин`
		let title = `🤖 Generated by IDE-BAS in ${formatMinutes(summary.totalDuration)}`
		if (summary.totalTimeSaved > 0) {
			title += ` • Saved ${formatMinutes(summary.totalTimeSaved)}`
		}

		// Create CodeLens at line 0 (first line)
		const range = new vscode.Range(0, 0, 0, 0)
		const codeLens = new vscode.CodeLens(range, {
			title: title,
			command: "ide-bas.showArtifactTimingHistory",
			arguments: [document.uri.fsPath],
			tooltip: "Click to view generation history",
		})

		return [codeLens]
	}

	/**
	 * Call this method to refresh CodeLens after saving new timing
	 */
	refresh(): void {
		this._onDidChangeCodeLenses.fire()
	}
}

